steps:
# Install dependencies
- name: 'python:3.11'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt', '--user']

# Deploy the Cloud Function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud functions deploy cv_optimizer \
        --gen2 \
        --runtime=python311 \
        --region=europe-west2 \
        --source=. \
        --entry-point=cv_optimizer \
        --trigger-http

# Set IAM policy for the function to restrict access
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Allow function to be invoked by allUsers for now - change this to specific accounts
      # as needed for more restricted access
      gcloud functions add-iam-policy-binding cv_optimizer \
        --gen2 \
        --region=europe-west2 \
        --member=serviceAccount:hireable-places@appspot.gserviceaccount.com \
        --role=roles/cloudfunctions.invoker

# Optional timeout for the entire build
timeout: '1800s'  # 30 minutes 